---
title: 'acetaminophen'
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
      df_print: paged

---

```{r, echo = FALSE}
knitr::opts_chunk$set( echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center')
library(DT)
```





```{r}
res_report <- readRDS('/var/folders/g8/bj644x7d0jn2zwwwjc2qwkxr0000gn/T//RtmpYzATWW/2023-12-07-141218_res_diffusion.Rds')
```



# Most connected node from signature input
```{r}
datatable(res_report$degree_signature)
```

# Drugs
## Drug info
```{r}
datatable(res_report$drugs)
```
## Drug target
```{r}
datatable(res_report$drugs.targets)
```
## Drug Side Effects
```{r}
datatable(res_report$drugs.side_effect)
```
## Drug shortest distance to signature
```{r}
datatable(res_report$drug.dist.signature)
```

# Pathways
## Pathway infos
```{r}
datatable(res_report$pathways)
```
## Pathways shortest distance to signature
```{r}
datatable(res_report$pathway.dist.signature)
```

# GO terms hepatox
## GO terms infos
```{r}
datatable(res_report$pathway.dist.signature)
```
## GO shortest distance to signature
```{r}
datatable(res_report$pathway.dist.signature)
```



