# Generate comparison_ora_gsea.rda
#
# Pre-computes ORA and GSEA enrichment results for acetaminophen (APAP) and
# valproic acid (VPA), filtered to the hepatotoxicity-specific background
# (GOTox / Reactome pathways) present in liver_1.7_network.
#
# Input files (not shipped with the package):
#   - data/liver_1.7_network.rda        (package data)
#   - data/signature_maison.rda         (package data)
#   - <project>/papier/result_use_case_paper.Rda
#       contains res_report_aceta and res_report_valpro (report() outputs)
#       → generated by data-raw/result_use_case_paper.R
#   - <project>/results/signature_maison_acetaminopheme_a_valproic.Rds
#       contains full DE results with log2FoldChange for GSEA scoring
#
# Run order:
#   1. source("data-raw/result_use_case_paper.R")   # ~30-60 min
#   2. source("data-raw/comparison_ora_gsea.R")     # ~10 min

library(tidyverse)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ReactomePA)

# --- Paths -------------------------------------------------------------------

path_report    <- file.path("..", "LO_cosmetic_europe", "papier",
                            "result_use_case_paper.Rda")
path_signature <- file.path("..", "LO_cosmetic_europe", "results",
                            "signature_maison_acetaminopheme_a_valproic.Rds")

# --- Load inputs -------------------------------------------------------------

data("liver_1.7_network", package = "CENetwork")
data("signature_maison",  package = "CENetwork")

load(path_report)                                          # res_report_aceta, res_report_valpro
list_signature_s368 <- readRDS(path_signature)             # full DE results with log2FoldChange

sig_aceto  <- signature_maison$acetaminophen_all_all
sig_valpro <- signature_maison$`valproic acid_all_all`

# --- Network-specific backgrounds --------------------------------------------

GOTox <- igraph::vertex_attr(liver_1.7_network) |>
  as.data.frame() |>
  dplyr::filter(type == "GO") |>
  dplyr::pull(name)

pathway_background <- igraph::vertex_attr(liver_1.7_network) |>
  as.data.frame() |>
  dplyr::filter(type == "pathway") |>
  dplyr::pull(name)

# --- Helpers -----------------------------------------------------------------

run_ora_go <- function(sig) {
  clusterProfiler::enrichGO(
    gene          = sig,
    keyType       = "ENSEMBL",
    OrgDb         = org.Hs.eg.db,
    ont           = "all",
    pAdjustMethod = "none",
    pvalueCutoff  = 1,
    qvalueCutoff  = 1
  )@result |>
    dplyr::filter(ID %in% GOTox) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr")) |>
    dplyr::filter(qvalue < 0.05)
}

run_ora_reactome <- function(sig) {
  entrez <- AnnotationDbi::select(
    org.Hs.eg.db, keys = sig, keytype = "ENSEMBL", columns = "ENTREZID"
  ) |> na.omit() |> dplyr::pull(ENTREZID) |> unique()

  ReactomePA::enrichPathway(
    gene = entrez, pvalueCutoff = 1, pAdjustMethod = "none", readable = TRUE
  )@result |>
    dplyr::filter(ID %in% pathway_background) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr")) |>
    dplyr::filter(qvalue < 0.05)
}

make_gsea_scores <- function(df_name) {
  df <- list_signature_s368[[df_name]] |> as.data.frame()
  scores <- df$log2FoldChange
  names(scores) <- stringr::str_remove(rownames(df), "_.*")
  sort(na.omit(scores), decreasing = TRUE)
}

run_gsea_go <- function(scores) {
  clusterProfiler::gseGO(
    geneList     = scores,
    OrgDb        = org.Hs.eg.db,
    keyType      = "ENSEMBL",
    ont          = "all",
    pvalueCutoff = 1,
    verbose      = FALSE
  )@result |>
    dplyr::filter(ID %in% GOTox) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr")) |>
    dplyr::filter(qvalue < 0.05)
}

run_gsea_reactome <- function(scores) {
  scores_entrez <- scores |>
    as.data.frame() |>
    stats::setNames("score") |>
    tibble::rownames_to_column("ENSEMBL") |>
    dplyr::left_join(
      AnnotationDbi::select(org.Hs.eg.db, keys = names(scores),
                            keytype = "ENSEMBL", columns = "ENTREZID"),
      by = "ENSEMBL"
    ) |>
    na.omit() |>
    dplyr::group_by(ENTREZID) |>
    dplyr::summarise(score = median(score), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(score)) |>
    tibble::deframe()

  ReactomePA::gsePathway(
    scores_entrez, pvalueCutoff = 1, pAdjustMethod = "none", verbose = FALSE
  )@result |>
    dplyr::filter(ID %in% pathway_background) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr")) |>
    dplyr::filter(qvalue < 0.05)
}

# --- Run analyses ------------------------------------------------------------

message("ORA GO...")
ora_go_apap <- run_ora_go(sig_aceto)
ora_go_vpa  <- run_ora_go(sig_valpro)

message("ORA Reactome...")
ora_reactome_apap <- run_ora_reactome(sig_aceto)
ora_reactome_vpa  <- run_ora_reactome(sig_valpro)

message("GSEA scores...")
scores_apap <- make_gsea_scores("acetaminophen_all")
scores_vpa  <- make_gsea_scores("valproic_acid_all")

message("GSEA GO...")
set.seed(123)  # for reproducibility of GSEA p-values
gsea_go_apap <- run_gsea_go(scores_apap)
gsea_go_vpa  <- run_gsea_go(scores_vpa)

message("GSEA Reactome...")
set.seed(123)  # for reproducibility of GSEA p-values
gsea_reactome_apap <- run_gsea_reactome(scores_apap)
gsea_reactome_vpa  <- run_gsea_reactome(scores_vpa)

# --- Assemble and save -------------------------------------------------------

comparison_ora_gsea <- list(
  # Diffusion significant terms (from report())
  diffusion_go_apap      = unique(res_report_aceta$GOs$name),
  diffusion_go_vpa       = unique(res_report_valpro$GOs$name),
  diffusion_pathway_apap = unique(res_report_aceta$pathways$name),
  diffusion_pathway_vpa  = unique(res_report_valpro$pathways$name),

  # ORA – GO (filtered to GOTox, re-FDR, qvalue < 0.05)
  ora_go_apap = ora_go_apap,
  ora_go_vpa  = ora_go_vpa,

  # GSEA – GO (filtered to GOTox, re-FDR, qvalue < 0.05)
  gsea_go_apap = gsea_go_apap,
  gsea_go_vpa  = gsea_go_vpa,

  # ORA – Reactome (filtered to pathway_background, re-FDR, qvalue < 0.05)
  ora_reactome_apap = ora_reactome_apap,
  ora_reactome_vpa  = ora_reactome_vpa,

  # GSEA – Reactome (filtered to pathway_background, re-FDR, qvalue < 0.05)
  gsea_reactome_apap = gsea_reactome_apap,
  gsea_reactome_vpa  = gsea_reactome_vpa
)

save(comparison_ora_gsea,
     file     = "data/comparison_ora_gsea.rda",
     compress = "xz")

message("Saved: data/comparison_ora_gsea.rda")
message(sprintf("  GOTox background   : %d terms", length(GOTox)))
message(sprintf("  Pathway background : %d terms", length(pathway_background)))
message(sprintf("  ORA GO  APAP/VPA   : %d / %d", nrow(ora_go_apap),       nrow(ora_go_vpa)))
message(sprintf("  GSEA GO APAP/VPA   : %d / %d", nrow(gsea_go_apap),      nrow(gsea_go_vpa)))
message(sprintf("  ORA  RT APAP/VPA   : %d / %d", nrow(ora_reactome_apap), nrow(ora_reactome_vpa)))
message(sprintf("  GSEA RT APAP/VPA   : %d / %d", nrow(gsea_reactome_apap),nrow(gsea_reactome_vpa)))

# --- Venn diagrams -----------------------------------------------------------

library(ggvenn)
library(patchwork)

venn_colors <- c("#fff9be", "#bdf4ff", "#ffbdda")

g1 <- ggvenn::ggvenn(
  data = list(
    "Diffusion" = comparison_ora_gsea$diffusion_go_apap,
    "ORA"       = comparison_ora_gsea$ora_go_apap$ID,
    "GSEA"      = comparison_ora_gsea$gsea_go_apap$ID
  ),
  fill_color = venn_colors, text_size = 8, set_name_size = 5,
  show_percentage = FALSE
) +
  ggplot2::ggtitle("A. Acetaminophen (GO terms)") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 15, face = "bold"))

g2 <- ggvenn::ggvenn(
  data = list(
    "Diffusion" = comparison_ora_gsea$diffusion_pathway_apap,
    "ORA"       = comparison_ora_gsea$ora_reactome_apap$ID,
    "GSEA"      = comparison_ora_gsea$gsea_reactome_apap$ID
  ),
  fill_color = venn_colors, text_size = 8, set_name_size = 5,
  show_percentage = FALSE
) +
  ggplot2::ggtitle("B. Acetaminophen (Reactome terms)") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 15, face = "bold"))

g3 <- ggvenn::ggvenn(
  data = list(
    "Diffusion" = comparison_ora_gsea$diffusion_go_vpa,
    "ORA"       = comparison_ora_gsea$ora_go_vpa$ID,
    "GSEA"      = comparison_ora_gsea$gsea_go_vpa$ID
  ),
  fill_color = venn_colors, text_size = 8, set_name_size = 5,
  show_percentage = FALSE
) +
  ggplot2::ggtitle("C. Valproic acid (GO terms)") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 15, face = "bold"))

g4 <- ggvenn::ggvenn(
  data = list(
    "Diffusion" = comparison_ora_gsea$diffusion_pathway_vpa,
    "ORA"       = comparison_ora_gsea$ora_reactome_vpa$ID,
    "GSEA"      = comparison_ora_gsea$gsea_reactome_vpa$ID
  ),
  fill_color = venn_colors, text_size = 8, set_name_size = 5,
  show_percentage = FALSE
) +
  ggplot2::ggtitle("D. Valproic acid (Reactome terms)") +
  ggplot2::theme(plot.title = ggplot2::element_text(size = 15, face = "bold"))

png("vignettes/img/comparison_venn.png", res = 300, width = 3000, height = 3000)
print((g1 + g2) / (g3 + g4))
dev.off()

message("Saved: vignettes/img/comparison_venn.png")

