# Generate comparison_ora_gsea.rda
#
# Pre-computes ORA and GSEA enrichment results for acetaminophen (APAP) and
# valproic acid (VPA), filtered to the hepatotoxicity-specific background
# (GOTox / Reactome pathways) present in liver_1.8_network.
#
# Input files (not shipped with the package):
#   - data/liver_1.8_network.rda        (package data)
#   - data/signature_maison.rda         (package data)
#   - <project>/papier/result_use_case_paper_1.8.Rda
#       contains res_report_aceta and res_report_valpro (report() outputs)
#       + enrich_apap / enrich_vpa (diffusion enrichment stats)
#       → generated by data-raw/result_use_case_paper.R
#   - <project>/results/signature_maison_acetaminopheme_a_valproic.Rds
#       contains full DE results with log2FoldChange for GSEA scoring
#
# Run order:
#   1. source("data-raw/result_use_case_paper.R")   # ~30-60 min
#   2. source("data-raw/comparison_ora_gsea.R")     # ~10 min

library(tidyverse)
library(clusterProfiler)
library(org.Hs.eg.db)
library(ReactomePA)

# --- Paths -------------------------------------------------------------------

path_report    <- file.path("~", "Documents", "Projects", "LO_cosmetic_europe",
                            "papier", "result_use_case_paper_1.8.Rda")
path_signature <- file.path("~", "Documents", "Projects", "LO_cosmetic_europe",
                            "results", "signature_maison_acetaminopheme_a_valproic.Rds")

# --- Load inputs -------------------------------------------------------------

# loaded from data/ rather than data(): the installed CENetwork build does not
# ship the 1.8 network yet
load("data/liver_1.8_network.rda")
load("data/signature_maison.rda")

load(path_report)                                          # res_report_aceta, res_report_valpro
list_signature_s368 <- readRDS(path_signature)             # full DE results with log2FoldChange

sig_aceto  <- signature_maison$acetaminophen_all_all
sig_valpro <- signature_maison$`valproic acid_all_all`

# --- Network-specific backgrounds --------------------------------------------

GOTox <- igraph::vertex_attr(liver_1.8_network) |>
  as.data.frame() |>
  dplyr::filter(type == "GO") |>
  dplyr::pull(name)

pathway_background <- igraph::vertex_attr(liver_1.8_network) |>
  as.data.frame() |>
  dplyr::filter(type == "pathway") |>
  dplyr::pull(name)

# --- Helpers -----------------------------------------------------------------
#
# The run_* helpers return every term the method could test within the network
# background, with its FDR-adjusted qvalue. Significance (qvalue < 0.05) is applied
# downstream, so that "tested but not significant" stays distinguishable from
# "never tested" (outside the ORA/GSEA universe, or node not visited by diffusion).

run_ora_go <- function(sig) {
  clusterProfiler::enrichGO(
    gene          = sig,
    keyType       = "ENSEMBL",
    OrgDb         = org.Hs.eg.db,
    ont           = "all",
    pAdjustMethod = "none",
    pvalueCutoff  = 1,
    qvalueCutoff  = 1
  )@result |>
    dplyr::filter(ID %in% GOTox) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr"))
}

run_ora_reactome <- function(sig) {
  entrez <- AnnotationDbi::select(
    org.Hs.eg.db, keys = sig, keytype = "ENSEMBL", columns = "ENTREZID"
  ) |> na.omit() |> dplyr::pull(ENTREZID) |> unique()

  ReactomePA::enrichPathway(
    gene = entrez, pvalueCutoff = 1, pAdjustMethod = "none", readable = TRUE
  )@result |>
    dplyr::filter(ID %in% pathway_background) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr"))
}

make_gsea_scores <- function(df_name) {
  df <- list_signature_s368[[df_name]] |> as.data.frame()
  scores <- df$log2FoldChange
  names(scores) <- stringr::str_remove(rownames(df), "_.*")
  sort(na.omit(scores), decreasing = TRUE)
}

run_gsea_go <- function(scores) {
  clusterProfiler::gseGO(
    geneList     = scores,
    OrgDb        = org.Hs.eg.db,
    keyType      = "ENSEMBL",
    ont          = "all",
    pvalueCutoff = 1,
    verbose      = FALSE
  )@result |>
    dplyr::filter(ID %in% GOTox) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr"))
}

run_gsea_reactome <- function(scores) {
  scores_entrez <- scores |>
    as.data.frame() |>
    stats::setNames("score") |>
    tibble::rownames_to_column("ENSEMBL") |>
    dplyr::left_join(
      AnnotationDbi::select(org.Hs.eg.db, keys = names(scores),
                            keytype = "ENSEMBL", columns = "ENTREZID"),
      by = "ENSEMBL"
    ) |>
    na.omit() |>
    dplyr::group_by(ENTREZID) |>
    dplyr::summarise(score = median(score), .groups = "drop") |>
    dplyr::arrange(dplyr::desc(score)) |>
    tibble::deframe()

  ReactomePA::gsePathway(
    scores_entrez, pvalueCutoff = 1, pAdjustMethod = "none", verbose = FALSE
  )@result |>
    dplyr::filter(ID %in% pathway_background) |>
    dplyr::mutate(qvalue = p.adjust(pvalue, method = "fdr"))
}

# --- Run analyses ------------------------------------------------------------

message("ORA GO...")
ora_go_apap_all <- run_ora_go(sig_aceto)
ora_go_vpa_all  <- run_ora_go(sig_valpro)

message("ORA Reactome...")
ora_reactome_apap_all <- run_ora_reactome(sig_aceto)
ora_reactome_vpa_all  <- run_ora_reactome(sig_valpro)

message("GSEA scores...")
scores_apap <- make_gsea_scores("acetaminophen_all")
scores_vpa  <- make_gsea_scores("valproic_acid_all")

message("GSEA GO...")
set.seed(123)  # for reproducibility of GSEA p-values
gsea_go_apap_all <- run_gsea_go(scores_apap)
gsea_go_vpa_all  <- run_gsea_go(scores_vpa)

message("GSEA Reactome...")
set.seed(123)  # for reproducibility of GSEA p-values
gsea_reactome_apap_all <- run_gsea_reactome(scores_apap)
gsea_reactome_vpa_all  <- run_gsea_reactome(scores_vpa)

# --- Assemble and save -------------------------------------------------------

sig_only <- function(res) dplyr::filter(res, qvalue < 0.05)

ora_go_apap       <- sig_only(ora_go_apap_all)
ora_go_vpa        <- sig_only(ora_go_vpa_all)
ora_reactome_apap <- sig_only(ora_reactome_apap_all)
ora_reactome_vpa  <- sig_only(ora_reactome_vpa_all)
gsea_go_apap       <- sig_only(gsea_go_apap_all)
gsea_go_vpa        <- sig_only(gsea_go_vpa_all)
gsea_reactome_apap <- sig_only(gsea_reactome_apap_all)
gsea_reactome_vpa  <- sig_only(gsea_reactome_vpa_all)

# Diffusion significant terms, thresholded like ORA/GSEA (padj < 0.05).
# report()$GOs / $pathways list *every* term present in the subnetwork, which is
# not comparable to the q < 0.05 sets of the other two methods.
diffusion_sig <- function(enrich, term_type) {
  enrich$term[enrich$type == term_type & enrich$padj < 0.05] |> na.omit() |> unique()
}

# Terms each method actually tested. Needed to tell "tested but not significant"
# apart from "never tested" — a distinction a Venn diagram cannot show.
diffusion_tested <- function(enrich, term_type) {
  enrich$term[enrich$type == term_type] |> na.omit() |> unique()
}

comparison_ora_gsea <- list(
  # Diffusion significant terms (from compute_diffusion_enrichment(), padj < 0.05)
  diffusion_go_apap      = diffusion_sig(enrich_apap, "GO"),
  diffusion_go_vpa       = diffusion_sig(enrich_vpa,  "GO"),
  diffusion_pathway_apap = diffusion_sig(enrich_apap, "pathway"),
  diffusion_pathway_vpa  = diffusion_sig(enrich_vpa,  "pathway"),

  # ORA – GO (filtered to GOTox, re-FDR, qvalue < 0.05)
  ora_go_apap = ora_go_apap,
  ora_go_vpa  = ora_go_vpa,

  # GSEA – GO (filtered to GOTox, re-FDR, qvalue < 0.05)
  gsea_go_apap = gsea_go_apap,
  gsea_go_vpa  = gsea_go_vpa,

  # ORA – Reactome (filtered to pathway_background, re-FDR, qvalue < 0.05)
  ora_reactome_apap = ora_reactome_apap,
  ora_reactome_vpa  = ora_reactome_vpa,

  # GSEA – Reactome (filtered to pathway_background, re-FDR, qvalue < 0.05)
  gsea_reactome_apap = gsea_reactome_apap,
  gsea_reactome_vpa  = gsea_reactome_vpa,

  # Full result tables (every term tested within the network background, with qvalue)
  full = list(
    ora_go_apap = ora_go_apap_all,             ora_go_vpa = ora_go_vpa_all,
    ora_reactome_apap = ora_reactome_apap_all, ora_reactome_vpa = ora_reactome_vpa_all,
    gsea_go_apap = gsea_go_apap_all,           gsea_go_vpa = gsea_go_vpa_all,
    gsea_reactome_apap = gsea_reactome_apap_all, gsea_reactome_vpa = gsea_reactome_vpa_all,
    diffusion_go_apap      = diffusion_tested(enrich_apap, "GO"),
    diffusion_go_vpa       = diffusion_tested(enrich_vpa,  "GO"),
    diffusion_pathway_apap = diffusion_tested(enrich_apap, "pathway"),
    diffusion_pathway_vpa  = diffusion_tested(enrich_vpa,  "pathway")
  )
)

save(comparison_ora_gsea,
     file     = "data/comparison_ora_gsea.rda",
     compress = "xz")

message("Saved: data/comparison_ora_gsea.rda")
message(sprintf("  GOTox background   : %d terms", length(GOTox)))
message(sprintf("  Pathway background : %d terms", length(pathway_background)))
message(sprintf("  ORA GO  APAP/VPA   : %d / %d", nrow(ora_go_apap),       nrow(ora_go_vpa)))
message(sprintf("  GSEA GO APAP/VPA   : %d / %d", nrow(gsea_go_apap),      nrow(gsea_go_vpa)))
message(sprintf("  ORA  RT APAP/VPA   : %d / %d", nrow(ora_reactome_apap), nrow(ora_reactome_vpa)))
message(sprintf("  GSEA RT APAP/VPA   : %d / %d", nrow(gsea_reactome_apap),nrow(gsea_reactome_vpa)))

# --- Figure: term x method dot plot ------------------------------------------
#
# Replaces the former 3-set Venn diagrams. On liver_1.8 no panel has a triple
# intersection and pairwise overlaps are 0-2 terms, so a Venn spends a full page
# drawing empty regions. A Venn also cannot separate a term a method *tested and
# rejected* from one it never tested (outside its universe, or a node the diffusion
# never visited) — here that is an explicit third state.
#
# Colours are the project's method palette (Okabe-Ito), shared with the benchmark
# figures. Point area encodes -log10(q); the three methods use different statistics
# (permutation z-score, hypergeometric test, weighted KS), so areas are comparable
# within a method, not across.

library(ggplot2)

METHOD_COL <- c(Diffusion = "#009E73", ORA = "#E69F00", GSEA = "#CC79A7")

node_labels <- igraph::vertex_attr(liver_1.8_network) |>
  as.data.frame() |>
  dplyr::select(name, display_name)

cc      <- comparison_ora_gsea
enrichs <- list(APAP = enrich_apap, VPA = enrich_vpa)

panels <- list(
  list(compound = "APAP", ontology = "GO",       diff = "GO",      ora = "ora_go_apap",       gsea = "gsea_go_apap"),
  list(compound = "APAP", ontology = "Reactome", diff = "pathway", ora = "ora_reactome_apap", gsea = "gsea_reactome_apap"),
  list(compound = "VPA",  ontology = "GO",       diff = "GO",      ora = "ora_go_vpa",        gsea = "gsea_go_vpa"),
  list(compound = "VPA",  ontology = "Reactome", diff = "pathway", ora = "ora_reactome_vpa",  gsea = "gsea_reactome_vpa")
)

# every term each method tested in this panel, with its q-value
tested_terms <- function(p) {
  d <- enrichs[[p$compound]] |>
    dplyr::filter(type == p$diff) |>
    dplyr::transmute(term, q = padj)
  o <- cc$full[[p$ora]]  |> dplyr::transmute(term = ID, q = qvalue)
  g <- cc$full[[p$gsea]] |> dplyr::transmute(term = ID, q = qvalue)

  dplyr::bind_rows(Diffusion = d, ORA = o, GSEA = g, .id = "method") |>
    dplyr::mutate(panel = paste(p$compound, "·", p$ontology))
}

dat_tested <- purrr::map_dfr(panels, tested_terms) |>
  dplyr::mutate(status = ifelse(!is.na(q) & q < 0.05,
                                "significant", "tested, not significant"))

# Rows = every term significant for at least one method, no truncation. Ranking by
# q would be misleading here: the GSEA hits on APAP are dominated by a redundant
# cluster of nested Reactome translation sets (12 of them tie at q = 5e-09), which
# a top-N would show at the expense of the bioactivation pathways (Biological
# oxidations, Phase I, Xenobiotics, Cytochrome P450) that sit further down the list.
kept <- dat_tested |>
  dplyr::filter(status == "significant") |>
  dplyr::group_by(panel, term) |>
  dplyr::summarise(q_min = min(q), .groups = "drop")

dat <- kept |>
  tidyr::expand_grid(method = names(METHOD_COL)) |>
  dplyr::left_join(dat_tested, by = c("panel", "term", "method")) |>
  dplyr::mutate(
    # ORA reports only gene sets sharing >= 1 gene with the signature, so a term
    # missing from its @result has a zero overlap — i.e. p = 1, a result rather than
    # an absence of test. Only the diffusion (node never visited) and GSEA (gene set
    # outside the 10-500 gene range it scores) genuinely leave a term untested.
    q        = ifelse(is.na(q) & method == "ORA", 1, q),
    status   = dplyr::case_when(
      !is.na(status)  ~ status,
      method == "ORA" ~ "tested, not significant",
      TRUE            ~ "not tested"
    ),
    fill_key = ifelse(status == "significant", method, "none"),
    # every point needs a size, otherwise geom_point silently drops it — the two
    # non-significant states are exactly what this figure exists to show. A term
    # tested and nearly significant stays visibly bigger than one at q ~ 1.
    psize    = ifelse(status == "not tested", 0, -log10(pmax(q, 1e-12)))
  ) |>
  dplyr::left_join(node_labels, by = c("term" = "name")) |>
  dplyr::mutate(
    label  = stringr::str_wrap(dplyr::coalesce(display_name, term), 52),
    # zero-width space keeps the factor unique per panel while showing the bare name.
    # Facet rows read top-to-bottom, so ascending q_min puts the strongest term first.
    y_key  = forcats::fct_reorder(paste0(label, "​", panel), q_min),
    method = factor(method, levels = names(METHOD_COL)),
    status = factor(status, levels = c("significant", "tested, not significant", "not tested"))
  )

fig <- ggplot(dat, aes(x = method, y = y_key)) +
  geom_point(aes(shape = status, fill = fill_key, size = psize, colour = status),
             stroke = 0.4) +
  scale_colour_manual(
    values = c("significant" = "grey25", "tested, not significant" = "grey60",
               "not tested" = "grey80"),
    guide  = "none"
  ) +
  scale_shape_manual(
    values = c("significant" = 21, "tested, not significant" = 21, "not tested" = 4),
    name   = NULL,
    guide  = guide_legend(order = 1, override.aes = list(
      size = 3, fill = c("grey30", "white", NA), colour = c("grey30", "grey65", "grey80")))
  ) +
  scale_fill_manual(values = c(METHOD_COL, none = "white"), guide = "none") +
  scale_size(range = c(1.2, 6), limits = c(0, NA),
             name = expression(-log[10] ~ q), guide = guide_legend(order = 2)) +
  # terms carried by an inner strip rather than by the y axis, so each one sits in its
  # own framed band. facet_nested (ggh4x) merges the repeated outer strip, which plain
  # facet_grid would print once per row.
  ggh4x::facet_nested(
    rows     = vars(panel, y_key),
    scales   = "free_y", space = "free_y", switch = "y",
    labeller = labeller(y_key = function(x) sub("​.*", "", x)),
    strip    = ggh4x::strip_nested(bleed = FALSE)
  ) +
  labs(
    x = NULL, y = NULL,
    title = paste("Terms retained by network diffusion, ORA and GSEA in",
                  "acetaminophen (APAP) and valproic acid (VPA)")
  ) +
  # theme_bw-like: framed panels and filled strips, so the four compound x ontology
  # blocks read as separate categories
  theme_bw(base_size = 10) +
  theme(
    panel.border       = element_rect(colour = "grey55", fill = NA, linewidth = 0.4),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_line(colour = "grey90", linewidth = 0.3),
    panel.grid.minor   = element_blank(),
    panel.spacing.y    = grid::unit(0, "lines"),
    strip.placement    = "outside",
    strip.background   = element_rect(fill = "grey95", colour = "grey55", linewidth = 0.4),
    # outer strip = compound x ontology, inner strip = term
    strip.text.y.left  = element_text(angle = 0, hjust = 0, size = 8,
                                      margin = margin(2, 4, 2, 4)),
    axis.text.x        = element_text(face = "bold"),
    axis.text.y        = element_blank(),
    axis.ticks.y       = element_blank(),
    plot.title.position = "plot",
    legend.position    = "right",
    legend.key.height  = grid::unit(0.8, "lines")
  )

png("vignettes/img/comparison_dotplot.png", res = 300, width = 2900, height = 6300)
print(fig)
dev.off()

message("Saved: vignettes/img/comparison_dotplot.png")

# --- Supplementary table: diffusion / ORA / GSEA side by side -----------------

node_labels <- igraph::vertex_attr(liver_1.8_network) |>
  as.data.frame() |>
  dplyr::select(name, display_name)

diffusion_table <- function(enrich, term_type) {
  enrich |>
    dplyr::filter(type == term_type) |>
    dplyr::arrange(padj) |>
    dplyr::left_join(node_labels, by = c("term" = "name")) |>
    dplyr::select(term, display_name, visit_count, mean_perm, sd_perm,
                  z_score, pvalue, padj)
}

list_results <- list(
  APAP_diffusion_GO       = diffusion_table(enrich_apap, "GO"),
  APAP_diffusion_REACTOME = diffusion_table(enrich_apap, "pathway"),
  APAP_ORA_GO             = ora_go_apap,
  APAP_ORA_REACTOME       = ora_reactome_apap,
  APAP_GSEA_GO            = gsea_go_apap,
  APAP_GSEA_REACTOME      = gsea_reactome_apap,

  VPA_diffusion_GO        = diffusion_table(enrich_vpa, "GO"),
  VPA_diffusion_REACTOME  = diffusion_table(enrich_vpa, "pathway"),
  VPA_ORA_GO              = ora_go_vpa,
  VPA_ORA_REACTOME        = ora_reactome_vpa,
  VPA_GSEA_GO             = gsea_go_vpa,
  VPA_GSEA_REACTOME       = gsea_reactome_vpa
)

dir.create("results", showWarnings = FALSE)
openxlsx::write.xlsx(list_results, file = "results/comparison_ora_gsea.xlsx",
                     overwrite = TRUE)

message("Saved: results/comparison_ora_gsea.xlsx")

